project:
  type: website
  output-dir: site
execute:
  freeze: false
  cache: true
  warning: false
website:
  page-navigation: true
  bread-crumbs: true


  search:
    show-item-context: true
    type: overlay

  navbar:
    background: primary
    logo: op_logo.svg

    left:
      - text: "StatsOP.jl"
        href: index.qmd      
      - text: "OPs"
        href: page_files/op.qmd
      - text: "SOPs"
        href: page_files/sop.qmd
      - text: "GOPs"
        href: page_files/gop_tutorials.qmd
      - text: "API"
        href: page_files/api_reference.qmd

    tools:
    - icon: github
      href: https://github.com/AdaemmerP/StatsOP.jl
      text: "StatsOP.jl"

  sidebar:
    - title: "API"    
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - page_files/api_reference.qmd
        - section: "Types for ordinal patterns"
          contents:
            - reference/AR1.qmd
            - reference/MA1.qmd
            - reference/MA2.qmd
            - reference/TEAR1.qmd
            - reference/QAR1.qmd
        - section: "Types for generalized ordinal patterns"
          contents:  
        - section: "Types for spatial ordinal patterns"
          contents:
            - reference/SAR11.qmd
            - reference/SINAR11.qmd
            - reference/SAR1.qmd
            - reference/SQINMA11.qmd
            - reference/SQMA11.qmd
        - section: "Functions for ordinal patterns"
          contents:
            - reference/arl_op.qmd
            - reference/cl_op.qmd    
        - section: "Functions for spatial ordinal patterns"
          contents:
            - reference/arl_sop.qmd
            - reference/arl_sacf.qmd
    - title: "SOPs"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - page_files/sop.qmd
        - page_files/sop_tutorial.qmd
        - page_files/sop_replication.qmd   
    - title: "OPs"
      style: "docked"
      background: light
      contents:
        - page_files/op.qmd
        #- page_files/op_dependence.qmd
        #- page_files/op_changepoint.qmd
        #- page_files/op_tutorial.qmd
        #- page_files/op_replication.qmd                 

  page-footer: "Website generated with [Quarto](https://quarto.org/) and [QuartoDocBuilder.jl](https://github.com/vituri/QuartoDocBuilder.jl)"


engine: julia

format:
  html:
    theme: pulse # cosmo flatly materia minty pulse spacelab
    css: styles.css
    code-copy: true
    code-overflow: wrap
    preview-links: true
    toc: true
    toc-depth: 3
    toc-expand: true 
