---
engine: julia
---

# rl_sacf_bp_ic {#sec-doc}
    

::: {.callout-note appearance="simple" title="docblock" collapse=false}    


```{julia}
#| eval: false
rl_sacf_bp_ic(

```

lam, cl, sp*dgp::ICSP, d1*vec::Vector{Int}, d2*vec::Vector{Int}, p*reps::UnitRange, dist_error::UnivariateDistribution )
 
Compute the out-of-control run length using the spatial autocorrelation function  (SACF) for the BP-statistic. The function returns the run length for a given control    limit `cl` and a given number of repetitions `reps`. The input arguments are:
 
  * `sp_dgp::ICSP`: The in-control spatial data generating process (DGP) to use for
the SACF function. 
 
  * `lam`: The smoothing parameter for the exponentially weighted moving average
(EWMA) control chart.
 
  * `cl`: The control limit for the EWMA control chart.
  * `d1_vec::Vector{Int}`: The first (row) delays for the spatial process.
  * `d2_vec::Vector{Int}`: The second (column) delays for the spatial process.
  * `p_reps::UnitRange`: The number of repetitions to compute the run length. This
has to be a unit range of integers to allow for parallel processing, since the    function is called by `arl_sacf()`.
 
  * `dist_error::UnivariateDistribution`: The distribution to use for the error term
in the spatial process. This can be any univariate distribution from the `Distributions.jl` package.
 


:::
    

