---
engine: julia
---

# rl_sop_bp {#sec-doc}
    

::: {.callout-note appearance="simple" title="docblock" collapse=false}    


```{julia}
#| eval: false
rl_sop_bp(

```

lam, cl, lookup*array*sop, spatial*dgp::ICSP, reps*range, dist, chart*choice,    d1*vec::Vector{Int}, d2_vec::Vector{Int} )
 
Computes the run length for a given in-control spatial DGP, using the EWMA-BP-SOP statistic.
 
The input parameters are:
 
  * `lam::Float64`: A scalar value for lambda for the EWMA chart.
  * `cl::Float64`: A scalar value for the control limit.
  * `lookup_array_sop::Array{Int, 4}`: A 4D array with the lookup array for the sops,
which will be computed computed using `lookup_array_sop = compute_lookup_array_sop()`.
 
  * `spatial_dgp::ICSP`: A struct for the in-control spatial DGP.
  * `reps_range::UnitRange{Int}`: A range of integers for the number of repetitions.
  * `dist::Distribution`: A distribution for the error term. Here you can use any
univariate distribution from the `Distributions.jl` package.
 
  * `chart_choice::Int`: An integer value for the chart choice. The options are 1-4.
  * `d1_vec::Vector{Int}`: A vector with integer values for the first delay (d₁).
  * `d2_vec::Vector{Int}`: A vector with integer values for the second delay (d₂).


:::
    

 --- 
 
::: {.callout-note appearance="simple" title="docblock" collapse=false}    


```{julia}
#| eval: false
rl_sop_bp(

```

lam, cl, lookup*array*sop, p*reps, spatial*dgp::SpatialDGP, dist*error::UnivariateDistribution,   dist*ao::Union{Nothing,UnivariateDistribution}, chart*choice, d1*vec::Vector{Int}, d2_vec::Vector{Int} )
 
Computes the run length for a given out-of-control DGP, using the EWMA-BP-SOP statistic.
 
The input parameters are:
 
  * `lam::Float64`: A scalar value for lambda for the EWMA chart.
  * `cl::Float64`: A scalar value for the control limit.
  * `lookup_array_sop::Array{Int, 4}`: A 4D array with the lookup array for the sops,
which will be computed computed using `lookup_array_sop = compute_lookup_array_sop()`.
 
  * `p_reps::UnitRange{Int}`: A range of integers for the number of repetitions.
  * `spatial_dgp::SpatialDGP`: A struct for the out-of-control spatial DGP.
  * `dist_error::UnivariateDistribution`: A distribution for the error term. Here you can use any
univariate distribution from the `Distributions.jl` package.
 
  * `dist_ao::Union{Nothing,UnivariateDistribution}`: A distribution for the additive outlier.
  * `chart_choice::Int`: An integer value for the chart choice. The options are 1-4.
  * `d1_vec::Vector{Int}`: A vector with integer values for the first delay (d₁).
  * `d2_vec::Vector{Int}`: A vector with integer values for the second delay (d₂).


:::
    

