---
engine: julia
---

# SINAR11 {#sec-doc}
    

::: {.callout-note appearance="simple" title="docblock" collapse=false}    


```{julia}
#| eval: false
SINAR11(dgp_params, M_rows, N_cols, dist, dist_ao, prerun)

```

A struct to define a first-order integer spatial autoregressive (SINAR(1, 1)) model:
 
$\qquad X_{t_1, t_2}=\alpha_1 \circ X_{t_1-1, t_2}+\alpha_2 \circ X_{t_1, t_2-1}+\alpha_3 \circ X_{t_1-1, t_2-1}+\varepsilon_{t_1, t_2}.$ 
 
  * `dgp_params::Tuple(α₁::Float64, α₂::Float64, α₃::Float64)` Note that α₁, α₂, and α₃ ∈ [0, 1) and α₁ + α₂ + α₃ < 1 to guarantee stationarity.
  * `m::Int` The number of rows for the final "SOP" matrix. Note that the final spatial matrix ("picture") equals m + 1.
  * `n::Int` The number of columns for the final "SOP" matrix. Note that the final spatial matrix ("picture") equals n + 1.
  * `prerun::Int` A value to initialize the DGP to guarantee stationarity. These number of rows and columns will be discarded for the final spatial matrix.
  * `dist::Distribution` A distribution for \varepsilon*{t*1, t_2}. You can use any univariate distribution from the `Distributions.jl` package.
  * `dist_ao::Union{Nothing, Distribution}` Nothing or a distribution for additive outliers. For additive outliers you can use any univariate distribution from the `Distributions.jl` package.
  * `prerun::Int` A value to initialize the DGP to achieve stationarity. These number of rows and columns will be discarded after the initialization.

```{julia}
#| eval: false
sar11 = SINAR((0.5, 0.3, 0.2), 11, 11, 100)

```



:::
    

